# Generated by Django 2.2.7 on 2020-05-13 12:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kitchen', 'Кухня'), ('client', 'Клиент')], default='client', max_length=50, verbose_name='Тип Чека')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('rendered', 'Готов'), ('printed', 'Распечатан')], default='new', max_length=50, verbose_name='Статус')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='')),
                ('order', django.contrib.postgres.fields.jsonb.JSONField()),
                ('printer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_r', to='printers.Printer')),
            ],
        ),
    ]
