# Generated by Django 2.2.7 on 2020-05-13 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
                ('api_key', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='API_KEY')),
                ('check_type', models.CharField(choices=[('kitchen', 'Кухня'), ('client', 'Клиент')], default='client', max_length=50, verbose_name='Тип Чека')),
                ('point_id', models.IntegerField(blank=True, null=True, verbose_name='Точка привязки')),
            ],
        ),
    ]
